/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminapp;

/**
 *
 * @author Nina
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablePing = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPing = new javax.swing.JTextArea();
        cardLayout = new javax.swing.JPanel();
        options = new javax.swing.JPanel();
        editBillsButton = new javax.swing.JButton();
        editMenuButton1 = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        editBills = new javax.swing.JPanel();
        table1 = new javax.swing.JButton();
        toOptionsListButton = new javax.swing.JButton();
        bills = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        priceText = new javax.swing.JTextArea();
        confirmButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemText = new javax.swing.JTextArea();
        editBillButton = new javax.swing.JButton();
        tableName = new javax.swing.JLabel();
        toTableListButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablePing.setBackground(new java.awt.Color(255, 255, 255));
        tablePing.setForeground(new java.awt.Color(255, 255, 255));

        textPing.setEditable(false);
        textPing.setColumns(20);
        textPing.setRows(5);
        jScrollPane1.setViewportView(textPing);

        javax.swing.GroupLayout tablePingLayout = new javax.swing.GroupLayout(tablePing);
        tablePing.setLayout(tablePingLayout);
        tablePingLayout.setHorizontalGroup(
            tablePingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        tablePingLayout.setVerticalGroup(
            tablePingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        cardLayout.setBackground(new java.awt.Color(153, 255, 204));
        cardLayout.setLayout(new java.awt.CardLayout());

        editBillsButton.setBackground(new java.awt.Color(255, 255, 255));
        editBillsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editBillsButton.setText("Edit Bills");
        editBillsButton.setMaximumSize(new java.awt.Dimension(100, 75));
        editBillsButton.setMinimumSize(new java.awt.Dimension(100, 75));
        editBillsButton.setPreferredSize(new java.awt.Dimension(100, 75));
        editBillsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBillsButtonActionPerformed(evt);
            }
        });

        editMenuButton1.setBackground(new java.awt.Color(255, 255, 255));
        editMenuButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editMenuButton1.setText("Edit Menu");
        editMenuButton1.setMaximumSize(new java.awt.Dimension(100, 75));
        editMenuButton1.setMinimumSize(new java.awt.Dimension(100, 75));
        editMenuButton1.setPreferredSize(new java.awt.Dimension(100, 75));
        editMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuButton1ActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setMaximumSize(new java.awt.Dimension(100, 75));
        exitButton.setMinimumSize(new java.awt.Dimension(100, 75));
        exitButton.setPreferredSize(new java.awt.Dimension(100, 75));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBillsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
            .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsLayout.createSequentialGroup()
                    .addContainerGap(155, Short.MAX_VALUE)
                    .addComponent(editMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(121, 121, 121)))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(editBillsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(optionsLayout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(editMenuButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(270, Short.MAX_VALUE)))
        );

        cardLayout.add(options, "card2");

        table1.setBackground(new java.awt.Color(255, 255, 255));
        table1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table1.setText("Table 1");
        table1.setMaximumSize(new java.awt.Dimension(100, 75));
        table1.setMinimumSize(new java.awt.Dimension(100, 75));
        table1.setPreferredSize(new java.awt.Dimension(100, 75));
        table1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                table1ActionPerformed(evt);
            }
        });

        toOptionsListButton.setBackground(new java.awt.Color(255, 255, 255));
        toOptionsListButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        toOptionsListButton.setText("Back");
        toOptionsListButton.setMaximumSize(new java.awt.Dimension(100, 75));
        toOptionsListButton.setMinimumSize(new java.awt.Dimension(100, 75));
        toOptionsListButton.setPreferredSize(new java.awt.Dimension(100, 75));
        toOptionsListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toOptionsListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editBillsLayout = new javax.swing.GroupLayout(editBills);
        editBills.setLayout(editBillsLayout);
        editBillsLayout.setHorizontalGroup(
            editBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBillsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(editBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toOptionsListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        editBillsLayout.setVerticalGroup(
            editBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editBillsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addComponent(toOptionsListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cardLayout.add(editBills, "card2");

        priceText.setColumns(20);
        priceText.setRows(5);
        priceText.setMaximumSize(new java.awt.Dimension(120, 94));
        priceText.setMinimumSize(new java.awt.Dimension(120, 94));
        priceText.setPreferredSize(new java.awt.Dimension(120, 94));
        jScrollPane2.setViewportView(priceText);

        confirmButton.setBackground(new java.awt.Color(255, 255, 255));
        confirmButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.setMaximumSize(new java.awt.Dimension(100, 75));
        confirmButton.setMinimumSize(new java.awt.Dimension(100, 75));
        confirmButton.setPreferredSize(new java.awt.Dimension(100, 75));
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        itemText.setColumns(20);
        itemText.setRows(5);
        jScrollPane3.setViewportView(itemText);

        editBillButton.setBackground(new java.awt.Color(255, 255, 255));
        editBillButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editBillButton.setText("Edit Bill");
        editBillButton.setMaximumSize(new java.awt.Dimension(100, 75));
        editBillButton.setMinimumSize(new java.awt.Dimension(100, 75));
        editBillButton.setPreferredSize(new java.awt.Dimension(100, 75));
        editBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBillButtonActionPerformed(evt);
            }
        });

        tableName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tableName.setText("Table 1");

        toTableListButton.setBackground(new java.awt.Color(255, 255, 255));
        toTableListButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        toTableListButton.setText("Back");
        toTableListButton.setMaximumSize(new java.awt.Dimension(100, 75));
        toTableListButton.setMinimumSize(new java.awt.Dimension(100, 75));
        toTableListButton.setPreferredSize(new java.awt.Dimension(100, 75));
        toTableListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toTableListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout billsLayout = new javax.swing.GroupLayout(bills);
        bills.setLayout(billsLayout);
        billsLayout.setHorizontalGroup(
            billsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billsLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
            .addGroup(billsLayout.createSequentialGroup()
                .addComponent(tableName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(toTableListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );
        billsLayout.setVerticalGroup(
            billsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billsLayout.createSequentialGroup()
                .addGroup(billsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(billsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableName)
                    .addComponent(toTableListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cardLayout.add(bills, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tablePing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_table1ActionPerformed
        // TODO add your handling code here:
        
        cardLayout.removeAll();
        cardLayout.repaint();
        
        cardLayout.add(bills);
        cardLayout.repaint();
        cardLayout.revalidate();
    }//GEN-LAST:event_table1ActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void editBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBillButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBillButtonActionPerformed

    private void toTableListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toTableListButtonActionPerformed
        // TODO add your handling code here:
        
        cardLayout.removeAll();
        cardLayout.repaint();
        
        cardLayout.add(editBills);
        cardLayout.repaint();
        cardLayout.revalidate();
    }//GEN-LAST:event_toTableListButtonActionPerformed

    private void toOptionsListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toOptionsListButtonActionPerformed
        // TODO add your handling code here:
        
        cardLayout.removeAll();
        cardLayout.repaint();
        
        cardLayout.add(options);
        cardLayout.repaint();
        cardLayout.revalidate();
    }//GEN-LAST:event_toOptionsListButtonActionPerformed

    private void editBillsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBillsButtonActionPerformed
        // TODO add your handling code here:
        cardLayout.removeAll();
        cardLayout.repaint();
        
        cardLayout.add(editBills);
        cardLayout.repaint();
        cardLayout.revalidate();
    }//GEN-LAST:event_editBillsButtonActionPerformed

    private void editMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editMenuButton1ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bills;
    private javax.swing.JPanel cardLayout;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton editBillButton;
    private javax.swing.JPanel editBills;
    private javax.swing.JButton editBillsButton;
    private javax.swing.JButton editMenuButton1;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextArea itemText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel options;
    private javax.swing.JTextArea priceText;
    private javax.swing.JButton table1;
    private javax.swing.JLabel tableName;
    private javax.swing.JPanel tablePing;
    private javax.swing.JTextArea textPing;
    private javax.swing.JButton toOptionsListButton;
    private javax.swing.JButton toTableListButton;
    // End of variables declaration//GEN-END:variables
}
